from django.urls import path, include
from . import views

urlpatterns = [
    path('',views.home, name='home'),
    path('register_users/',views.UsersRegister.as_view(), name='register_users'),
    path('register_country/',views.CountryRegister.as_view(), name='register_country'),
    path('register_discover/', views.DiscoverRegister.as_view(), name='register_discover'),
    path('register_disease/', views.DiseaseRegister.as_view(), name='register_disease'),
    path('register_diseaseType/', views.DiseaseTypeRegister.as_view(), name='register_diseaseType'),
    path('register_doctor/', views.DoctorRegister.as_view(), name='register_doctor'),
    path('register_public/', views.PublicServantRegister.as_view(), name='register_public'),
    path('register_record/', views.RecordRegister.as_view(), name='register_record'),
    path('register_specialize/', views.SpecializeRegister.as_view(), name='register_specialize'),
    path('users_list/', views.UsersList.as_view(), name='users_list'),
    path('country_list/', views.CountryList.as_view(), name='country_list'),
    path('diseasetype_list/', views.DiseaseTypeList.as_view(), name='diseasetype_list'),
    path('disease_list/', views.DiseaseList.as_view(), name='disease_list'),
    path('discovery_list/', views.DiscoveryList.as_view(), name='discovery_list'),
    path('doctor_list/', views.DoctorList.as_view(), name='doctor_list'),
    path('specialize_list/', views.SpecializeList.as_view(), name='specialize_list'),
    path('public_list/', views.PublicServantList.as_view(), name='public_list'),
    path('record_list/', views.RecordList.as_view(), name='record_list'),
    path('updateUser/<str:pk>/', views.updateUsers, name='updateUser'),
    path('updateCountry/<str:pk>/', views.updateCountry, name='updateCountry'),
    path('updateDiseaseType/<str:pk>/', views.updateDiseaseType, name='updateDiseaseType'),
    path('updateDisaese/<str:pk>/', views.updateDisease, name='updateDisease'),
    path('updateDiscovery/<str:cname>/<str:disease_code>/', views.updateDiscovery, name='updateDiscovery'),
    path('updateDiscovery/<str:cname>/<str:disease_code>/', views.updateDiscovery, name='updateDiscovery'),
    path('updateDoctor/<str:pk>/', views.updateDoctor, name='updateDoctor'),
    path('updateSpecialize/<int:id>/<str:email>/', views.updateSpecialize, name='updateSpecialize'),
    path('updateRecord/<str:cname>/<str:email>/<str:disease_code>/', views.updateRecord, name='updateRecord'),
    path('updatePublic/<str:pk>/', views.updatePublic, name='updatePublic'),
    path('deleteUsers/<str:pk>/', views.deleteUsers, name='deleteUsers'),
    path('deleteCountry/<str:pk>/', views.deleteCountry, name='deleteCountry'),
    path('deleteDiseaseType/<str:pk>/', views.deleteDiseaseType, name='deleteDiseaseType'),
    path('deleteDisease/<str:pk>/', views.deleteDisease, name='deleteDisease'),
    path('deleteDiscovery/<str:cname>/<str:disease_code>/', views.deleteDiscovery, name='deleteDiscovery'),
    path('deleteDoctor/<str:pk>/', views.deleteDoctor, name='deleteDoctor'),
    path('deleteSpecialize/<int:id>/<str:email>/', views.deleteSpecialize, name='deleteSpecialize'),
    path('deleteRecord/<str:cname>/<str:email>/<str:disease_code>', views.deleteRecord, name='deleteRecord'),
    path('deletePublic/<str:pk>/', views.deletePublic, name='deletePublic'),
]